%YAML:1.0
#--------------------------------------------------------------------------------------------------------- 
#pointcloud_generate: path of input rgb
#--------------------------------------------------------------------------------------------------------- 
rgb_path: /home/fishmarch/myProject/ManhattanTracking/data/tum_fine_rgb.png

#--------------------------------------------------------------------------------------------------------- 
#pointcloud_generate: path of input depth
#--------------------------------------------------------------------------------------------------------- 
depth_path: /home/fishmarch/myProject/ManhattanTracking/data/tum_fine_depth.png

#--------------------------------------------------------------------------------------------------------- 
#pointcloud_generate: path of output point cloud
#normal_estimation: path of input point cloud
#normal_estimation: path of input point cloud
#--------------------------------------------------------------------------------------------------------- 
pcd_path: /home/fishmarch/myProject/ManhattanTracking/data/tum_fine_cloud_unorder.pcd

#---------------------------------------------------------------------------------------------------------
#normal_estimation: path of output normal
#---------------------------------------------------------------------------------------------------------
gaussian_path: /home/fishmarch/myData/TUM/rgbd_dataset_freiburg3_cabinet/normalCloud/rgb/1341841278.pcd
gaussian_path2: /home/fishmarch/myData/TUM/rgbd_dataset_freiburg3_cabinet/normalCloud/rgb/1341841279.pcd

#---------------------------------------------------------------------------------------------------------
#normal_estimation: whether save output normal cloud
#---------------------------------------------------------------------------------------------------------
save_output: 0

#---------------------------------------------------------------------------------------------------------
#tum_gaussian: path of output normal  PATH_TO_SEQUENCE_FOLDER ASSOCIATIONS_FILE
#---------------------------------------------------------------------------------------------------------
associations_file: /home/fishmarch/myData/TUM/rgbd_dataset_freiburg3_cabinet/short.txt
sequence_folder: /home/fishmarch/myData/TUM/rgbd_dataset_freiburg3_cabinet

#---------------------------------------------------------------------------------------------------------
#normal_estimation: size of VoxelGrid filter's leaf
#---------------------------------------------------------------------------------------------------------
grid_size: 0.03

#---------------------------------------------------------------------------------------------------------
#initilize: time of initilize meanshift points
#---------------------------------------------------------------------------------------------------------
initilize_time: 100

#---------------------------------------------------------------------------------------------------------
#initilize: window size to compute the distance
#---------------------------------------------------------------------------------------------------------
window_size: 0.4

UseGaussianCore: 1
#---------------------------------------------------------------------------------------------------------
#pointcloud_generate: camera parameters
#---------------------------------------------------------------------------------------------------------   
camera_factor: 5000
camera_fx: 535.4
camera_fy: 539.2 
camera_cx: 320.1 
camera_cy: 247.6

#--------------------------------------------------------------------------------------------------------- 
#pointcloud_generate: flag to generate ordered cloud(1) or not(0)
#--------------------------------------------------------------------------------------------------------- 
order: 0
